n=[1,2,2,2,2,3,3,3,4,4]
print(n)
print(len(n))
print("1 count in list",n.count(1))
print("2 count in list",n.count(2)) 
print("3 count in list",n.count(3))
print("index of 1 is",n.index(1))
n.append(100)
print(n)
n.insert(1,200)
print(n)
n1=["hello","how","are","you!"]
n.extend(n1)
print(n)
n.remove(1)
print(n)
print(n.pop())
print(n.pop())
print(n)
n.reverse()
print(n)
n1=[1,8,3,9,2,5]
n1.sort()
print(n1)
print(3 in n1)
print(3 not in n1)
print(10 not in n1)